# Prometheus values для установки
server:
  service:
    type: NodePort
    nodePort: 30090
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

alertmanager:
  enabled: true
  service:
    type: NodePort
    nodePort: 30093
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

grafana:
  enabled: false  # У нас уже есть отдельный Grafana
