---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  # Сервис типа NodePort для доступа извне
  service_type: NodePort
  nodeport_port: 30800
  
  # Hostname для AWX
  hostname: awx.local
  
  # Persistent storage для проектов
  projects_persistence: true
  projects_storage_size: 8Gi
  projects_storage_access_mode: ReadWriteOnce
  
  # Admin пользователь
  admin_user: admin
  admin_password_secret: awx-admin-password
  
  # Ресурсы для web контейнера (адаптированы под Kind)
  web_resource_requirements:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 1Gi
  
  # Ресурсы для task контейнера (адаптированы под Kind)
  task_resource_requirements:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 1Gi
  
  # PostgreSQL ресурсы (адаптированы под Kind)
  postgres_resource_requirements:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 512Mi
  
  postgres_storage_requirements:
    requests:
      storage: 8Gi

